import {defineType, defineField, defineArrayMember} from 'sanity'
import {MdPerson as icon} from 'react-icons/md'
import {slugValidation} from './utils/slugValidation'

export const aboutPage = defineType({
  name: 'aboutPage',
  title: 'About Page',
  type: 'document',
  icon,
  groups: [
    {name: 'general', title: 'General'},
    {name: 'seo', title: 'SEO'},
    {name: 'reel', title: 'Sizzle Reel'},
    {name: 'section1', title: 'Section 1'},
    {name: 'section2', title: 'Section 2'},
    {name: 'services', title: 'Services'},
    {name: 'adFormats', title: 'Ad Formats'},
    {name: 'company3', title: 'Company3'},
    {name: 'director', title: 'Director'},
    {name: 'team', title: 'Team'},
    {name: 'utahLocations', title: 'Utah Locations'},
    {name: 'ravensCards', title: 'Ravens Cards'},
    {name: 'brands', title: 'Brands'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'general',
    }),
    defineField({
      name: 'slug',
      title: 'Slug (should-be-kebab-case-like-this)',
      type: 'slug',
      validation: slugValidation,
      options: {
        source: 'title',
        maxLength: 100,
      },
      group: 'general',
    }),
    defineField({
      name: 'seoTitle',
      title: 'SEO Title',
      type: 'string',
      group: 'seo',
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO Description',
      type: 'text',
      group: 'seo',
    }),
    defineField({
      name: 'poster',
      title: 'Poster',
      type: 'image',
      options: {hotspot: true},
      group: 'general',
    }),
    defineField({
      name: 'videoId',
      title: 'Video id',
      type: 'string',
      description:
        'Enter the ID ( {{video_id}} ) of the video, not the whole url. https://player.vimeo.com/video/{{video_id}}?badge=0&autopause=0&player_id=0&app_id=58479',
      group: 'general',
    }),
    defineField({
      name: 'headerVideoWidthInPixels',
      title: 'Header video width in pixels',
      type: 'number',
      group: 'general',
    }),
    defineField({
      name: 'headerVideoHeightInPixels',
      title: 'Header video height in pixels',
      type: 'number',
      group: 'general',
    }),
    defineField({
      name: 'videoIdMobile',
      title: 'Video ID (mobile)',
      type: 'string',
      description: 'Video ID to use on mobile. Leave blank to use the "Video ID" above on mobile',
      group: 'general',
    }),
    defineField({
      name: 'headerVideoWidthInPixelsMobile',
      title: 'Header video width in pixels (mobile)',
      type: 'number',
      group: 'general',
    }),
    defineField({
      name: 'headerVideoHeightInPixelsMobile',
      title: 'Header video height in pixels (mobile)',
      type: 'number',
      group: 'general',
    }),
    defineField({
      name: 'subtitle',
      title: 'Subtitle',
      type: 'string',
      group: 'general',
    }),
    defineField({
      name: 'reelVideoSectionTitle',
      title: 'Reel video section title',
      description: 'Title above the reel video section',
      type: 'string',
      group: 'reel',
    }),
    defineField({
      name: 'reelVideoSectionSubtitle',
      title: 'Reel video section subtitle',
      description: 'Subtitle above the reel video section',
      type: 'string',
      group: 'reel',
    }),
    defineField({
      name: 'reelVideoTitle',
      title: 'Reel video title',
      type: 'string',
      group: 'reel',
    }),
    defineField({
      name: 'reelVideoClient',
      title: 'Reel video client',
      type: 'string',
      group: 'reel',
    }),
    defineField({
      name: 'reelVideoDescription',
      title: 'Reel video description',
      type: 'text',
      group: 'reel',
    }),
    defineField({
      name: 'reelVideoId',
      title: 'Reel video id',
      type: 'string',
      group: 'reel',
    }),
    defineField({
      name: 'reelVideoIdShort',
      title: 'Reel video id (short)',
      type: 'string',
      group: 'reel',
    }),
    defineField({
      name: 'reelVideoWidthInPixels',
      title: 'Reel video width in pixels',
      type: 'number',
      group: 'reel',
    }),
    defineField({
      name: 'reelVideoHeightInPixels',
      title: 'Reel video height in pixels',
      type: 'number',
      group: 'reel',
    }),
    defineField({
      name: 'reelVideoWidthAspectRatio',
      title: 'Reel video aspect ratio for width',
      type: 'string',
      description: 'What is the width of the aspect ratio',
      options: {
        list: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'],
        layout: 'dropdown',
      },
      group: 'reel',
    }),
    defineField({
      name: 'reelVideoHeightAspectRatio',
      title: 'Reel video aspect ratio for height',
      type: 'string',
      description: 'What is the height of the aspect ratio',
      options: {
        list: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'],
        layout: 'dropdown',
      },
      group: 'reel',
    }),
    defineField({
      name: 'reelVideoPoster',
      title: 'Reel poster image',
      type: 'image',
      options: {hotspot: true},
      group: 'reel',
    }),
    defineField({
      name: 'section1Title',
      title: 'Section 1 title',
      type: 'string',
      group: 'section1',
    }),
    defineField({
      name: 'section1Body',
      title: 'Section 1 body',
      type: 'array',
      of: [defineArrayMember({type: 'block'})],
      group: 'section1',
    }),
    defineField({
      name: 'section1Subtitle',
      title: 'Section 1 subtitle',
      type: 'string',
      group: 'section1',
    }),
    defineField({
      name: 'section1Images',
      title: 'Images',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'image',
          fields: [
            defineField({
              name: 'caption',
              type: 'string',
              title: 'Caption',
            }),
          ],
        }),
      ],
      group: 'section1',
    }),
    defineField({
      name: 'section2Title',
      title: 'Section 2 title',
      type: 'string',
      group: 'section2',
    }),
    defineField({
      name: 'section2Subtitle',
      title: 'Section 2 subtitle',
      type: 'string',
      group: 'section2',
    }),
    defineField({
      name: 'services',
      title: 'Services',
      type: 'array',
      of: [defineArrayMember({type: 'reference', to: [{type: 'service'}]})],
      group: 'services',
    }),
    defineField({
      name: 'adFormatsTitle',
      title: 'Ad Formats Section Title',
      type: 'string',
      group: 'adFormats',
    }),
    defineField({
      name: 'adFormatsSubtitle',
      title: 'Ad Formats Section Subtitle',
      type: 'string',
      group: 'adFormats',
    }),
    defineField({
      name: 'adFormatsContent',
      title: 'Ad Formats Section Content',
      type: 'array',
      of: [defineArrayMember({type: 'block'})],
      group: 'adFormats',
    }),
    defineField({
      name: 'adFormats',
      title: 'Ad Formats',
      type: 'array',
      of: [defineArrayMember({type: 'adFormat'})],
      group: 'adFormats',
    }),
    defineField({
      name: 'company3VideoTitle',
      title: 'Company 3 video title',
      type: 'string',
      group: 'company3',
    }),
    defineField({
      name: 'company3VideoClient',
      title: 'Company 3 video client',
      type: 'string',
      group: 'company3',
    }),
    defineField({
      name: 'company3VideoDescription',
      title: 'Company 3 video description',
      type: 'text',
      group: 'company3',
    }),
    defineField({
      name: 'company3VideoId',
      title: 'Company 3 video id',
      type: 'string',
      group: 'company3',
    }),
    defineField({
      name: 'company3VideoIdShort',
      title: 'Company 3 video id (short)',
      type: 'string',
      group: 'company3',
    }),
    defineField({
      name: 'company3VideoWidthAspectRatio',
      title: 'Company 3 video aspect ratio for width',
      type: 'string',
      description: 'What is the width of the aspect ratio',
      options: {
        list: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'],
        layout: 'dropdown',
      },
      group: 'company3',
    }),
    defineField({
      name: 'company3VideoHeightAspectRatio',
      title: 'Company 3 video aspect ratio for height',
      type: 'string',
      description: 'What is the height of the aspect ratio',
      options: {
        list: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'],
        layout: 'dropdown',
      },
      group: 'company3',
    }),
    defineField({
      name: 'company3VideoPoster',
      title: 'Company 3 poster image',
      type: 'image',
      options: {hotspot: true},
      group: 'company3',
    }),
    defineField({
      name: 'company3Title',
      title: 'Company 3 title',
      type: 'string',
      group: 'company3',
    }),
    defineField({
      name: 'company3Body',
      title: 'Company 3 body',
      type: 'array',
      of: [defineArrayMember({type: 'block'})],
      group: 'company3',
    }),
    defineField({
      name: 'company3Link',
      title: 'Company 3 link',
      type: 'url',
      group: 'company3',
    }),
    defineField({
      name: 'directorImage',
      title: 'Director image',
      type: 'image',
      options: {hotspot: true},
      group: 'director',
    }),
    defineField({
      name: 'directorImageTitle',
      title: 'Director image title',
      type: 'string',
      group: 'director',
    }),
    defineField({
      name: 'directorImageSubtitle',
      title: 'Director image subtitle',
      type: 'string',
      group: 'director',
    }),
    defineField({
      name: 'directorTitle',
      title: 'Director title',
      type: 'string',
      group: 'director',
    }),
    defineField({
      name: 'directorName',
      title: 'Director name',
      type: 'string',
      group: 'director',
    }),
    defineField({
      name: 'directorDescription',
      title: 'Director description',
      type: 'array',
      of: [defineArrayMember({type: 'block'})],
      group: 'director',
    }),
    defineField({
      name: 'teamTitle',
      title: 'Team title',
      type: 'string',
      group: 'team',
    }),
    defineField({
      name: 'teamSubtitle',
      title: 'Team Subtitle',
      type: 'string',
      group: 'team',
    }),
    defineField({
      name: 'teamMembers',
      title: 'Team members',
      type: 'array',
      of: [defineArrayMember({type: 'reference', to: [{type: 'teamMember'}]})],
      group: 'team',
    }),
    defineField({
      name: 'utahLocationsTitle',
      title: 'Utah locations title',
      type: 'string',
      group: 'utahLocations',
    }),
    defineField({
      name: 'utahLocationsDescription',
      description: 'Utah locations title',
      type: 'array',
      of: [defineArrayMember({type: 'block'})],
      group: 'utahLocations',
    }),
    defineField({
      name: 'utahLocations',
      title: 'Utah Locations',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'image',
          fields: [
            defineField({
              name: 'caption',
              type: 'string',
              title: 'Caption',
            }),
          ],
        }),
      ],
      group: 'utahLocations',
    }),
    defineField({
      name: 'ravensCards',
      title: 'Ravens Cards',
      type: 'array',
      of: [defineArrayMember({type: 'ravensCard'})],
      group: 'ravensCards',
    }),
    defineField({
      name: 'ravensCardsTitle',
      title: 'Ravens Title',
      type: 'string',
      group: 'ravensCards',
    }),
    defineField({
      name: 'ravensCardsSubtitle',
      title: 'Ravens Subtitle',
      type: 'string',
      group: 'ravensCards',
    }),
    defineField({
      name: 'ravensCardsContent',
      title: 'Ravens Content',
      type: 'array',
      of: [defineArrayMember({type: 'block'})],
      group: 'ravensCards',
    }),
    defineField({
      name: 'brands',
      title: 'Brands',
      type: 'array',
      of: [defineArrayMember({type: 'reference', to: [{type: 'brand'}]})],
      group: 'brands',
    }),
  ],
  preview: {
    select: {
      title: 'title',
    },
    prepare() {
      return {
        title: 'About Page',
      }
    },
  },
})
